### ISSUE TITLE
Clean up properties

### ISSUE THREAD

**Issue by osteinhauer** [camunda/camunda-bpm-spring-boot-starter#146]
There are a bunch of properties (`CamundaBpmProperties`) which are just used for a 1:1 copy to the process engine configuration. A good example is the authorization configuration. With #138 we introduced a possibility to use all process engine properties in a _generic_ way.

If we transform this _generic_ way to the main way we achieve the following improvements:
- `CamundaBpmProperties` contains only extra properties which are used for configuration logic.
- Documentation for properties is not blown up with parts that should be documented by camunda.
- Increased compatibility with camunda versions (relaxed data binding must not throw exceptions when setters are missing).

**Comment by osteinhauer** [comment]
I have created a [branch](https://github.com/camunda/camunda-bpm-spring-boot-starter/tree/cleanup_properties) where I have implemented:

- removed unnecessary properties
- removed unnecessary documentation
- introduced relaxed process engine properties
- code completion in `application.(properties|yml)`

**Comment by jangalinski** [comment]
Hm ... I got this (after a while), but I am not sure I like it. I fear that the choice "which property is 'generic' and which is required for 'configuration logic'" is not strictly black/white so we will have discussions again. I liked the "everything that we do not support natively is still usable via generics", because that was more like a statement "we do not YET support it, but we will".

**Comment by jangalinski** [comment]
Hi Olli ... you became quit, hope you are well ... I am closing the PR for now, because I really think that important, commonly used properties like db-setup, authorizations and so on should be possible via direct yaml properties (and code completion!). The indicator  for "do we create a custom property element for it" or "do we use it via generics" should be the relevance, not the fact that we add stuff ...  Of course we can discuss this again in the future ...
