### ISSUE TITLE
Support Multi-Tenancy during deployment

### ISSUE THREAD

**Issue by falko** [camunda/camunda-bpm-spring-boot-starter#149]
Allow to deploy a process model to a specific tenant.

**Comment by jangalinski** [comment]
Although it would be nice to support this, may I ask what the use case is? From my point of view, running camunda in a spring boot container should help to run many contexts each on a different machine, while the multi-tenant feature does the opposite: run multiple contexts on one machine ...

**Comment by falko** [comment]
The motivation is to use the new multi-tenancy mechanism that allows multiple tenants in the same engine database: https://docs.camunda.org/manual/latest/user-guide/process-engine/multi-tenancy/#single-process-engine-with-tenant-identifiers

I discovered that it is already possible if one uses a ProcessApplication, because in that case the deployment can be configured through the `processes.xml` file.

**Comment by jangalinski** [comment]
Ah, ok, I see ... we will deprecate the "non-process-application" way with 2.0, since it saves a lot of troubles. But we also will have to make some platform changes so we can controll a "virtual processes.xml" via application.yaml, otherwise we have two configuration mechanisms.

Multi-Tenancy: I guess a scenario where 2 engines talk with one DB and use different tenants would be nice. Using two tenants on the same spring-boot engine does not feel right, since it violates the "one thing only" principle.

**Comment by aravindhrs** [comment]
can we have process engine, process definition and database schema for each tenant. i.e., per tenant providing separate resources. is this good practice?

For example:

Tenant 'A' -> ProcessEngine A, Processdefintion A, DatabaseSchema A
Tenant 'B' ->  ProcessEngine B, Processdefintion B, DatabaseSchema B

**Comment by falko** [comment]
@aravindhrs In general with Camunda yes, but not in Spring Boot. See also: https://docs.camunda.org/manual/latest/user-guide/process-engine/multi-tenancy/
