### ISSUE TITLE
use camundaBpmProperties in webapp and cloud

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-spring-boot-starter#182]
Currently, when trying to use the configurationProperties in other projects than the basic starter, we get a spring exception. Seems like the properties are created twice and thus do not work.

To work around this, we use value injection directly, but it would be nice to fix this.

**Comment by Zapata** [comment]
The issue should have the same root cause as #189.

**Comment by cwensel** [comment]
+1 on the this bug. took a while to figure out.

turns out the Configuration objects that @PostConstruct test that they are valid (e.g. adminUser is configured) will cause the whole stack to shutdown if Spring-Cloud-Config-Client is a dependency.

Note, the workaround is to put all camunda properties into the bootstrap.yml file.

**Comment by jangalinski** [comment]
Now this works, I guess it was related to spring hierarchy issues, see #244 for example.
