### ISSUE TITLE
@EnableProcessApplication interferes with inner static bean definitions

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-spring-boot-starter#187]
I marked my Spring Application with "EnableProcessApplication". Additionally, I created a static Bean method that provides a different configuration.

Result: Error, EnableProcessApplication must only be used on one bean.

Seems like finding the correct "root" bean is buggy.

**Comment by jangalinski** [comment]
created branch 187_static_bean_definitions with a failing test showing the problem. no fix though still

**Comment by osteinhauer** [comment]
Hi Jan.

This is because ``applicationContext.getBeansWithAnnotation(...)`` in ``org.camunda.bpm.spring.boot.starter.util.GetProcessApplicationNameFromAnnotation.getAnnotatedBean`` is searching the hole type definition in case of a bean definition (see ``org.springframework.beans.factory.support.DefaultListableBeanFactory.findAnnotationOnBean(String, Class<A>)``).

A solution could be to extend the ``getAnnotatedBean``function with a filter checking if the found beans are annotated with ``@EnableProcessApplication`` directly.

**Comment by jangalinski** [comment]
Thanks, @osteinhauer , great help. Was able to provide a simple stream/filter for this one, PR waiting.
Care to review?
