### ISSUE TITLE
Allow to run multiple engines

### ISSUE THREAD

**Issue by berndruecker** [camunda/camunda-bpm-spring-boot-starter#210]
If I am not completely mistaken it is currently only possible to run one engine via Spring Boot. That should be changed :-)

**Comment by jangalinski** [comment]
You are not mistaken, it is not supported. For me this is the same discussion as with #149 (multi tenancy), which we closed with a "wont fix" ... for me, being able to run camunda/tomcat in a spring boot container allows a "micro-engines"-architecture, so instead of having one node running multiple engines and tenants I would tend to have many nodes, each running one dedicated aspect.

So instead of just building "multi engine support", my question is: what would be the concrete advantage of supporting this?

**Comment by berndruecker** [comment]
I tend to agree. My current use case was to have a microservice monitoring other engines :-) But as the webapps are not really working well on Spring Boot anyway, it might be a better idea to not do this using Spring boot anyway.

**Comment by jangalinski** [comment]
Let's keep this in mind ...

**Comment by jangalinski** [comment]
I'll close this with "won't fix" for now to keep the backlog clean
