### ISSUE TITLE
Include Enterprise webapps when used with Gradle

### ISSUE THREAD

**Issue by stefanzilske** [camunda/camunda-bpm-spring-boot-starter#216]
When using the Spring Boot starter in a Gradle environment, the Enterprise-Webapps are not supported, since there is a custom Maven plugin to include the Enterprise-Webapps, but no equivalent for Gradle.

**Comment by jangalinski** [comment]
Happy to accept contributions, but we will not support gradle "officially" ... due to lack of know-how. But the plugin is just a "download dependency, extract, rearrange and copy" operation, so it should be easily possible to include st. similar into your build-file. Check the original pom.xml the plugin is based on: https://github.com/camunda/camunda-consulting/blob/master/snippets/camunda-webapp-webjar-ee/pom.xml

**Comment by stefanzilske** [comment]
Since I am afraid that we will need it in many places (aka. build files), I think I will try generalise it into a Gradle plugin, which can be shipped with the starter and just invoked from wherever needed.

**Comment by jangalinski** [comment]
As I said: happy to accept anything ... just not able to do it myself and no need to.
