### ISSUE TITLE
cleanup in example poms needed

### ISSUE THREAD

**Issue by osteinhauer** [camunda/camunda-bpm-spring-boot-starter#243]
found some _strange_ dependencies in poms like

```
<dependency>
      <groupId>com.h2database</groupId>
      <artifactId>h2</artifactId>
      <scope>compile</scope>
</dependency>
```
or
```
<dependency>
      <groupId>com.google.code.findbugs</groupId>
      <artifactId>findbugs</artifactId>
      <version>3.0.0</version>
</dependency>
```

**Comment by jangalinski** [comment]
I suppose h2 in compile scope is in the starter-test module? I would leave it there ... when you add the starter-test in test-scope to your application, you get all libraries you need for testing without adding additional libs .... that's expected behavior.

And the findbugs is a common annotation library that supports  @Nonnull and @Nullable ... which is quite useful.

**Comment by osteinhauer** [comment]
Found them in the cloud example pom. h2 should be in runtime scope and findbugs (annotations) are never used...

**Comment by jangalinski** [comment]
ok ... then I said nothing ... go ahead
