### ISSUE TITLE
allow deployment aware job executors

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-spring-boot-starter#25]

**Comment by osteinhauer** [comment]
Any news here?

**Comment by jangalinski** [comment]
I will try to setup a (manual) testcase this weekend. imho this should work out of the box, at least when using the SpringBootProcessApplication.

**Comment by jangalinski** [comment]
Always fun when you read about what you promised to do "next weekend" half a year after ...

**Comment by jangalinski** [comment]
It works, but adding an integration test is too much effort for now (docker, shared DB, ....) . just trust me :-)

It requires using the @EnableProcessEngine annotation, it will *not* work with the spring autoDeployment!

**Comment by Kelzama** [comment]
I can confirm that it works wit @enableprocessengine.

**Comment by icyerasor** [comment]
Are you talking about @EnableProcessApplication?
It will not work when isScanForProcessDefinitions is set to true. Is that what you refer to as "spring autoDeployment"?

**Comment by jangalinski** [comment]
Spring-AutoDeployment: spring does a classpath scan and deploys all files that match some extension-patterns. Deployment is not grouped and not linked to processApplication.
Consequences: processes can be used, but advanced features like deploymentAware jobExecutors and embedded forms won't work.

EnableProcessApplication: deployment scan is triggered by existing processes.xml (can be empty). Auto Deployment (s.a) is deactivated. isScanForProcessDefinitions defaults to true so bpmn resources are found and deployed.

Note: issue management has been moved to jira, it is a better solution to discuss general application features in the forum.

**Comment by icyerasor** [comment]
Thx for the super fast reply.
When using @EnableProcessApplication & isScanForProcessDefinitions=true; deployment aware job execution does not seem to work for me (using 2.2.0). When changing to isScanForProcessDefinitions=false and referencing the resources manually it works.

Is that to be expected? If it should work in both cases as long as EnableProcessApplication is used, I can open a Jira issue.

**Comment by jangalinski** [comment]
if you disable the scan, it is not supposed to work, since then no deployments are linked to the processApplication.
Set to `true`it should work, if it doesn't, yes, please go ahead and open an issue to verify. Please provide an example, so we can check the use case.

**Comment by icyerasor** [comment]
I investigated a little bit further with a minimal reproducer example and the issue seems not to be about isScanForProcessDefinitions=true/false, but what process definitions get deployed within the deployment bundles. If an exact same copy of a (sub)process gets deployed by two different instances/nodes, all of the processes in both bundles will be executed on both nodes.

Don't know if thats how its supposed to be, but seems rather surprising to me.

Minimal example [here](https://github.com/icyerasor/camunda-deployment-aware), Camunda-Jira-Issue created [here](https://app.camunda.com/jira/browse/CAM-8373).

**Comment by bmaehr** [comment]
I was search for many hours why deployment aware job executors didn't work like expected for me. 

The solution was finally a small thing: You need to set the deployment name (e.g. SpringProcessEngineConfiguration.setDeploymentName) otherwise both spring boot applications try to execute the processes of the last deploment.
