### ISSUE TITLE
Multi-Tenancy schema strategy

### ISSUE THREAD

**Issue by williamassoni** [camunda/camunda-bpm-spring-boot-starter#264]
Hi, we are using camunda-spring-boot (engine-rest/webapp) and found a problem, we have a application that will be used for a lot of clients and we need some data isolation in database.

We are creating a AWS application and we going to need to export and to import(backup/dump) specif data by custumers. It's difficulting the control by column identity strategy(tenant id), therefore in our case we're using database schema isolation(one schema per custumer).

We found a documentation about how camunda would resolved this problem and I found that I can configure many engines in one application (https://docs.camunda.org/manual/7.5/user-guide/process-engine/multi-tenancy).

Unfortunately I couldn't find this feature in camunda-spring-boot, actually the only thing that I found is create that engines "manually" using something like that:

```java
ProcessEngineConfigurationImpl configuration = new StandaloneProcessEngineConfiguration();
configuration.setIdGenerator(new StrongUuidGenerator());
configuration.setProcessEngineName(tenant);

configuration.setJdbcUrl("jdbc:postgresql://172.23.1.184:5432/camunda?currentSchema=camundades1");
configuration.setJdbcUsername("postgres");
configuration.setDatabaseSchemaUpdate(StandaloneProcessEngineConfiguration.DB_SCHEMA_UPDATE_CREATE);
configuration.setJobExecutorDeploymentAware(true);
configuration.setHistory(StandaloneProcessEngineConfiguration.HISTORY_FULL);
    
ProcessEngine processEngine = configuration.buildProcessEngine();

// start the process engine inside the container.
RuntimeContainerDelegate.INSTANCE.get().registerProcessEngine(processEngine);
```

There is another way to handler with many schemas in camunda spring boot?

**Comment by jangalinski** [comment]
Hi William. Tenants/multi-engine are not supported currently. We discussed this in the past, see #149 and #210 but closed with "wont fix" because we did not really see a use case since with the spring-boot process engine we think more of a micro-service or micro-platform approach meaning: why run multiple engines or multiple tenants on one node when you could just run an additional  node for that.

Feel free to reopen the discussion and tell us about your use case., I'd prefer using the forum for that: https://forum.camunda.org/c/community-extensions/spring-boot-starter ... see you there!

**Comment by ESegundoRolon** [comment]
@jangalinski Hello!, I am facing same issue here. I describe you my use-case and please consider to re-open this issue.
I work in a company that uses Camunda with spring-boot starter as part of Microservices Architecture in multi-site and multi-branding products. This means that we could have one brand, for example "Nike", starting BPM processes in multiples countries at the same time, all this deployed in one node of my cluster app.

So, my node is a micro-service that needs to handle all this by itself with different data-sources (i.e Schemas or even different database clusters), and running additional nodes is not an option since no more infrastructure could be added at this time or any time sooner.

We achieved this by-passing the spring-boot instantiation mode of the Process Engine, this leads to dependency injections issues of our dependencies but we managed to inject directly using Spring context.

My point is, why using spring-boot starter should lead to a reduction of Camunda features such as multi-tenancy with multiple data-sources? From my consideration it should really do not reduce or not support the features that Camunda offers.
We were thinking on upgrade to Camunda EE, so we would be paying for features that are not supported on camunda-springboot-starter? It should be delegate to us the possibility of adopt good micro-service architecture or not, and it should not be restricted by the framework provided.

Thanks for consider my point of view.

**Comment by jangalinski** [comment]
Hi Enrique. These issues on github are only here for historical reasons, please check app.camunda.com/jira for the new issue management and feel free to open this issue there again. Background: with 2.3 the extension became an official camunda product and the core dev team will work on all issues, its not longer up to me to decide which issue to re-open or close. Thanks and good luck!

**Comment by ESegundoRolon** [comment]
Thank you for the quick feedback. I created new issue: https://app.camunda.com/jira/browse/CAM-9422
