### ISSUE TITLE
Maven repository publishing

### ISSUE THREAD

**Issue by osteinhauer** [camunda/camunda-bpm-spring-boot-starter#34]
By now every module is published (see http://mvnrepository.com/artifact/org.camunda.bpm.extension). Shouldn't only the starter artifacts (`camunda-bpm-spring-boot-starter`,`camunda-bpm-spring-boot-starter-rest`,`camunda-bpm-spring-boot-starter-webapp`) be published?

**Comment by jangalinski** [comment]
I don't think we can split this if we are using a common root pom for extension an examples. What I did for an other community extension is to give the example-tree a different groupId: "org.camunda.bpm.extension.example". This way, they still get published, but they do not mess up the mvn repo view because they are positioned one layer deeper than the prod code.

**Comment by hawky-4s-** [comment]
I tried several approaches but there seems to be a problem with the maven release plugin not honoring the skip deployment for some modules. So I resorted to just rename them like @jangalinski did for one of his projects.
